services:
  db:
    image: postgres:16
    container_name: metamind-postgres
    restart: always
    environment:
      POSTGRES_USER: metamind
      POSTGRES_PASSWORD: metamind123
      POSTGRES_DB: metamind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
